version: "3.7"
services:
  mongo_db:
    container_name: seguradora_mdb
    image: "mongo:4.4.3"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: "seguradora"
    ports:
      - 27017:27017
  api_service:
    container_name: seguradora_srv
    image: "renatopalmeida/seguradoraapi_api_service:1.0.0"
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo_db:27017/seguradora
    depends_on:
      - mongo_db